config/routes.rb
Rails.application.routes.draw do
  devise_for :admins,
             controllers: {
               sessions: 'admins/sessions',
               passwords: 'admins/passwords',
               registrations: 'admins/registrations',
             }
  devise_for :users,
             controllers: {
               sessions: 'users/sessions',
               passwords: 'users/passwords',
               registrations: 'users/registrations',
             }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  namespace :api do
    namespace :v1, format: 'json' do
      resources :relationships, only: [:index, :create, :destroy]
      resources :bookmarks, only: [:index, :create, :destroy]
    end
  end

  # ========= ユーザー(public)のルーティング ================
  scope module: :public do
    root to: 'camps#index'
    get '/about' => 'homes#about'

    resources :ranks, only: [:index]
    resources :tags, only: [:index, :show]
    resources :camps, only: [:index, :show]
    resources :camp_items, only: [:index, :show]
    resources :camp_places, only: [:index, :show]
    resources :camp_item_values, only: [:new, :create]
    resources :camp_place_values, only: [:new, :create]

    resources :camp_places, only: [:index, :show] do
      resources :reservations, only: [:new, :create]
      post 'reservations/confirm' => 'reservations#confirm'
      resources :camp_place_values, only: [:index, :new, :create, :show, :destroy]
    end

    resources :camp_items, only: [:index, :show] do
      resources :camp_item_values, only: [:index, :new, :create, :show, :destroy]
    end

    resources :posts, only: [:index, :new, :create, :show, :destroy] do
      resource :favorites, only: [:create, :destroy]
      resources :post_comments, only: [:create, :destroy]
    end

    resources :users, only: [:index, :show, :edit, :update] do
      resources :bookmarks, only: [:index]
      resources :reservations, only: [:index, :show]
      resource :relationships, only: [:create, :destroy]
      member do
        get 'following'
        get 'followers'
        get 'favorites'
        get 'post'
      end
    end
  end

  # ========= 管理者(admin)のルーティング ================
  namespace :admins do
    resources :reservations, only: [:index, :show]
    resources :camp_places
    resources :camp_items
    resources :users, only: [:index, :show]
  end
end

app/models/camp_place.rb
class CampPlace < ApplicationRecord
  belongs_to :admin

  has_many :bookmarks, dependent: :destroy
  has_many :reservations, dependent: :destroy
  has_many :camp_place_values, dependent: :destroy
  has_many :post_images, dependent: :destroy

  validates :name, presence: true
  validates :introduction, presence: true, length: { maximum: 500 }
  validates :address, presence: true
  validates :fee, presence: true
  validates :post_images_images, presence: true

  accepts_attachments_for :post_images, attachment: :image

  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  def self.search(search)
    return CampPlace.all unless search
    CampPlace.where(['name LIKE ?', "%#{search}%"])
  end

  def self.rank
    CampPlace.find(CampPlaceValue.group(:camp_place_id).order('avg(rate) desc').limit(3).pluck(:camp_place_id))
  end
end

app/controllers/admins/camp_places_controller.rb
class Admins::CampPlacesController < ApplicationController
  before_action :authenticate_admin!

  def index
    @camp_places = CampPlace.all.page(params[:page]).per(10).order(id: "DESC")
  end

  def show
    @camp_place = CampPlace.find(params[:id])
  end

  def new
    @camp_place = CampPlace.new
  end

  def edit
    @camp_place = CampPlace.find(params[:id])
  end

  def create
    @camp_place = CampPlace.new(camp_place_params)
    @camp_place.admin_id = current_admin.id
    if @camp_place.save
      redirect_to admins_camp_places_path
    else
      render :new
    end
  end

  def update
    @camp_place = CampPlace.find(params[:id])
    if @camp_place.update(camp_place_params)
      redirect_to admins_camp_place_path(@camp_place)
    else
      render :edit
    end
  end

  def destroy
    @camp_place = CampPlace.find(params[:id])
    @camp_place.destroy
    redirect_to admins_camp_places_path
  end

  private

  def camp_place_params
    params.require(:camp_place).permit(:image, :name, :address, :introduction, :fee, post_images_images: [])
  end
end

app/helpers/camp_place_helper.rb
module CampPlaceHelper
end

app/views/admins/camp_places/edit.html.erb
<div class="container">
  <div class="row">
    <div class="all-content-inner">
      <div class="col-md-8 offset-md-2">
        <%= form_with model:  [:admins, @camp_place], local:true do |f| %>
          <div class="row">
           <%= render 'shared/error_messages', object: f.object %>
          </div>
          <div class="form-group">
            <%= f.label :キャンプ場の写真 %>
            <%= f.attachment_field :post_images_images, multiple: true, class: "form-control-file user_image" %>
          </div>
          <div class="form-group">
            <%= f.label :キャンプ場 %>
            <%= f.text_field :name, class: "form-control name" %>
          </div>
          <div class="form-group">
            <%= f.label :住所 %>
            <%= f.text_field :address, class: "form-control address" %>
          </div>
          <div class="form-group">
            <%= f.label :キャンプ場紹介 %>
            <%= f.text_area :introduction, class: "form-control introduction", size: "80x6" %>
          </div>
          <div class="form-group">
            <%= f.label :料金 %>
            <%= f.text_field :fee, class: "form-control fee" %>
          </div>
          <div class="form-group text-center mt-5">
            <%= f.submit "編集する", class: 'glyphicon glyphicon-home btn btn-success' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admins/camp_places/index.html.erb
<div class="container">
  <div class="row">
    <div class="all-content-inner">
      <div class="col-md-6 offset-md-1 mt-3">
        <h5 class="font-weight-bold text-center">キャンプ場投稿履歴</h5>
      </div>
      <div class="col-md-2 offset-md-2 mt-2">
        <%= link_to new_admins_camp_place_path do %>
          <i class="far fa-edit fa-3x post-btn"></i>
        <% end %>
      </div>
      <% @camp_places.each do |camp_place| %>
        <% camp_place.post_images.first(1).each  do |post_image| %>
        <div class="d-flex flex-wrap mt-5 ml-2">
          <div class="col-12">
            <%= link_to (attachment_image_tag post_image, :image, format: 'jpeg', size: "200x200", class: "rounded"), admins_camp_place_path(camp_place) %>
            <div class="col-12 mt-1">
              <%= camp_place.name %>
            </div>
          </div>
        </div>
        <% end %>
      <% end %>
      <div class="col-12 mt-4 offset-md-5">
        <%= paginate @camp_places, theme: 'twitter-bootstrap-4' %>
      </div>
    </div>
  </div>
</div>

app/views/admins/camp_places/new.html.erb
<div class="container">
  <div class="row">
    <div class="new-content-inner mt-5">
      <div class="col-md-12">
        <%= form_with model:  [:admins, @camp_place], local:true do |f| %>
          <div class="row">
           <%= render 'shared/error_messages', object: f.object %>
          </div>
          <div class="form-group">
            <%= f.label :キャンプ場の写真 %>
            <%= f.attachment_field :post_images_images, multiple: true, class: "form-control-file user_image" %>
          </div>
          <div class="form-group">
            <%= f.label :キャンプ場 %>
            <%= f.text_field :name, class: "form-control name" %>
          </div>
          <div class="form-group">
            <%= f.label :住所 %>
            <%= f.text_field :address, class: "form-control address" %>
          </div>
          <div class="form-group">
            <%= f.label :キャンプ場紹介 %>
            <%= f.text_area :introduction, class: "form-control introduction", size: "40x6" %>
          </div>
           <div class="form-group">
            <%= f.label :料金 %>
            <%= f.text_field :fee, class: "form-control fee" %>
          </div>
          <div class="form-group text-center mt-5">
            <%= f.submit "投稿する", class: 'glyphicon glyphicon-home btn btn-success' %>
          </div>
        <% end %>
  　　</div>
  　</div>
  </div>
</div>

app/views/admins/camp_places/show.html.erb
<div class="container">
  <div class="row">
    <div class="all-content-inner">
      <% @camp_place.post_images.each  do |post_image| %>
       <div class="d-flex flex-wrap mt-4 ml-2">
         <div class="col-md-12 offset-md-9">
           <%= attachment_image_tag post_image, :image, format: 'jpeg', size: "200x200", class: "rounded" %>
          </div>
        </div>
      <% end %>
      <div class="col-md-8 offset-md-2 mt-4">
        <table class="table">
          <tbody>
            <tr>
              <td></td>
              <td><%= @camp_place.name %></td>
            </tr>
            <tr>
              <td></td>
              <td><%= @camp_place.address %></td>
            </tr>
            <tr>
              <td></td>
              <td><%= @camp_place.introduction %></td>
            </tr>
            <tr>
              <td></td>
              <td>¥<%= @camp_place.fee %></td>
            </tr>
          </tbody>
        </table>
      </div>
      <div class="col-md-12 text-center">
        <%= link_to '編集する', edit_admins_camp_place_path(@camp_place), class: 'glyphicon glyphicon-home btn btn-success' %>
        <%= link_to '削除する', admins_camp_place_path(@camp_place), method: :delete, data:{ confirm: '本当に削除しますか？' }, class: 'glyphicon glyphicon-home btn btn-danger' %>
      </div>
    </div>
  </div>
</div>