config/routes.rb
Rails.application.routes.draw do
  devise_for :admins,
             controllers: {
               sessions: 'admins/sessions',
               passwords: 'admins/passwords',
               registrations: 'admins/registrations',
             }
  devise_for :users,
             controllers: {
               sessions: 'users/sessions',
               passwords: 'users/passwords',
               registrations: 'users/registrations',
             }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  namespace :api do
    namespace :v1, format: 'json' do
      resources :relationships, only: [:index, :create, :destroy]
      resources :bookmarks, only: [:index, :create, :destroy]
    end
  end

  # ========= ユーザー(public)のルーティング ================
  scope module: :public do
    root to: 'camps#index'
    get '/about' => 'homes#about'

    resources :ranks, only: [:index]
    resources :tags, only: [:index, :show]
    resources :camps, only: [:index, :show]
    resources :camp_items, only: [:index, :show]
    resources :camp_places, only: [:index, :show]
    resources :camp_item_values, only: [:new, :create]
    resources :camp_place_values, only: [:new, :create]

    resources :camp_places, only: [:index, :show] do
      resources :reservations, only: [:new, :create]
      post 'reservations/confirm' => 'reservations#confirm'
      resources :camp_place_values, only: [:index, :new, :create, :show, :destroy]
    end

    resources :camp_items, only: [:index, :show] do
      resources :camp_item_values, only: [:index, :new, :create, :show, :destroy]
    end

    resources :posts, only: [:index, :new, :create, :show, :destroy] do
      resource :favorites, only: [:create, :destroy]
      resources :post_comments, only: [:create, :destroy]
    end

    resources :users, only: [:index, :show, :edit, :update] do
      resources :bookmarks, only: [:index]
      resources :reservations, only: [:index, :show]
      resource :relationships, only: [:create, :destroy]
      member do
        get 'following'
        get 'followers'
        get 'favorites'
        get 'post'
      end
    end
  end

  # ========= 管理者(admin)のルーティング ================
  namespace :admins do
    resources :reservations, only: [:index, :show]
    resources :camp_places
    resources :camp_items
    resources :users, only: [:index, :show]
  end
end

app/views/shared/_active_posts.erb
<% posts.includes([:favorites]).each do |post| %>
  <div class="post-inner offset-md-1 mt-5">
    <%= link_to attachment_image_tag(post, :image, format: 'jpeg', size: "180x180", class: "rounded"), post_path(post.id) %>
    <div class="post-title col-12 mt-1">
      <%= post.title %>
    </div>
    <div class="row post-active">
      <i class="far fa-comment-dots comment-active"> <%= post.post_comments.count %></i>
      <div id="favorites_buttons_<%= post.id %>">
        <%= render partial: 'public/favorites/favorite', locals: {post: post} %>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_camp_item_value_forms.erb
  <%= render 'shared/value_forms', f: f %>

  <!-- 評価javascript -->
  <script>
  $('#star').raty({
    size     : 36,
    starOff:  '<%= asset_path('star-off.png') %>',
    starOn : '<%= asset_path('star-on.png') %>',
    starHalf: '<%= asset_path('star-half.png') %>',
    scoreName: 'camp_item_value[rate]',
    half: true,
  });
  </script>

app/views/shared/_camp_item_values.erb
  <div class="row col-12 offset-md-1 camp-value" id="star-rate2-<%= camp_item.id %>"></div>
  <script>
    $('#star-rate2-<%= camp_item.id %>').raty({
      size: 30,
      starOn: "<%= asset_path('star-on.png') %>",
      starOff: "<%= asset_path('star-off.png') %>",
      starHalf: "<%= asset_path('star-half.png') %>",
      half: true,
      readOnly: true,
      score: "<%= camp_item.camp_item_values.average(:rate).to_f.round(1) %>",
    });
  </script>

app/views/shared/_camp_items.erb
<div class="col-4 camp-content mt-4 ml-2">
  <%= link_to camp_item_path(camp_item) do %>
    <%= attachment_image_tag(camp_item, :image, format: 'jpeg', size: "190x190", class: "rounded") %>
      <div class="col-12 text-center mt-1">
        <%= camp_item.name %>
      </div>
    <%= render 'shared/camp_item_values', camp_item: camp_item %>
  <% end %>
</div>

app/views/shared/_camp_place_value_forms.erb
  <%= render 'shared/value_forms', f: f %>

  <!-- 評価javascript -->
  <script>
  $('#star').raty({
    size     : 36,
    starOff:  '<%= asset_path('star-off.png') %>',
    starOn : '<%= asset_path('star-on.png') %>',
    starHalf: '<%= asset_path('star-half.png') %>',
    scoreName: 'camp_place_value[rate]',
    half: true,
  });
  </script>

app/views/shared/_camp_place_values.erb
  <div class="row col-12 offset-md-1 camp-value" id="star-rate1-<%= camp_place.id %>"></div>
  <script>
    $('#star-rate1-<%= camp_place.id %>').raty({
      size: 30,
      starOn: "<%= asset_path('star-on.png') %>",
      starOff: "<%= asset_path('star-off.png') %>",
      starHalf: "<%= asset_path('star-half.png') %>",
      half: true,
      readOnly: true,
      score: "<%= camp_place.camp_place_values.average(:rate).to_f.round(1) %>",
    });
  </script>

app/views/shared/_camp_places.erb
<% camp_place.post_images.first(1).each  do |post_image| %>
  <div class="col-4 camp-content mt-4 ml-2">
    <%= link_to camp_place_path(camp_place) do %>
      <%= attachment_image_tag(post_image, :image, format: 'jpeg', size: "190x190", class: "rounded") %> <br />
      <div class="col-12 text-center mt-1">
        <%= camp_place.name %>
      </div>
      <%= render 'shared/camp_place_values', camp_place: camp_place %>
    <% end %>
  </div>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_posts.erb
<%= link_to post_path(post) do %>
  <%= attachment_image_tag(post, :image, format: 'jpeg', size: "190x190", class: "rounded") %>
  <div class="row">
    <div class="post-title col-9 mt-2 ml-4">
      <%= post.title %>
    </div>
    <div id="favorites_buttons_<%= post.id %>", class="mt-1">
      <%= render partial: 'public/favorites/favorite', locals: {post: post} %>
    </div>
  </div>
<% end %>

app/views/shared/_reservations.erb
  <div class="col-md-7 offset-md-2 mt-4">
    <table class="table table-bordered">
      <tr>
        <td class="col-xs-2 table-secondary">キャンプ場</td>
        <td><%= reservation.camp_place.name %></td>
      </tr>
      <tr>
        <td class="col-xs-2 table-secondary">利用人数(5名様まで)</td>
        <td><%= reservation.guest %>名</td>
      </tr>
      <tr>
        <td class="col-xs-2 table-secondary">利用日数</td>
        <td><%= reservation.day %></td>
      </tr>
      <tr>
        <td class="col-xs-2 table-secondary">料金</td>
        <td>¥<%= reservation.camp_place.fee %></td>
      </tr>
      <tr>
        <td class="col-xs-2 table-secondary">支払い方法</td>
        <td><%= reservation.payment_method %></td>
      </tr>
      <tr>
        <td class="col-xs-2 table-secondary">チェックイン</td>
        <td><%= l reservation.start_date %></td>
      </tr>
      <tr>
        <td class="col-xs-2 table-secondary">チェックアウト</td>
        <td><%= l reservation.end_date %></td>
      </tr>
      <tr>
        <td class="col-xs-2 table-secondary">合計金額</td>
        <td>¥<%= reservation.total_fee = reservation.camp_place.fee %></td>
      </tr>
    </table>
  </div>

app/views/shared/_users.erb
  <div class="row mt-5">
    <div class="col-md-10">
      <table class="table table-hover offset-md-1">
        <% users.each do |user| %>
          <tbody>
            <tr onclick='window.location="<%= user_path(user) %>"' role="link">
              <td>
                <%= attachment_image_tag(user, :profile_image, format: 'jpeg', fallback: "user_image.jpg", size:'50x50', class: "user-image") %>
              </td>
              <td><%= user.name %></td>
              <td>
                <%= link_to "#{user.followings.count} フォロー", following_user_path(user) %>
                <%= link_to "#{user.followers.count} フォロワー ", followers_user_path(user) %>
              </td>
            </tr>
          </tbody>
        <% end %>
      </table>
    </div>
  </div>

app/views/shared/_value_forms.erb
  <div class="row offset-md-2">
   <%= render 'shared/error_messages', object: f.object %>
  </div>
  <div class="col-12 mt-2 offset-md-1">
    <div class="form-group form-inline">
    　<p>タイトル</p><p class="required-form">※必須</p>
      <div class="ml-5"><%= f.text_field :title, size: "20", class: "form-control" %></div>
    </div>
    <div class="form-group form-inline ml-3" id="star">
      <%= f.label :rate, '評価 ', class:'form-label' %>
      <p class="required-form mt-3">※必須</p>
      <div class="offset-md-2">
        <%= f.hidden_field :rate, id: :review_star %>
      </div>
    </div>
    <div class="form-group form-inline">
    　<p class="value-detail">本文</p>
      <div class="ml-5"><%= f.text_area :review, size: "40x6", class: "form-control" %></div>
    </div>
  </div>
  <div class="col-md-12 mt-5">
    <%= f.submit '投稿する', class:"btn btn-success" %>
  </div>