config/routes.rb
Rails.application.routes.draw do
  devise_for :admins,
             controllers: {
               sessions: 'admins/sessions',
               passwords: 'admins/passwords',
               registrations: 'admins/registrations',
             }
  devise_for :users,
             controllers: {
               sessions: 'users/sessions',
               passwords: 'users/passwords',
               registrations: 'users/registrations',
             }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  namespace :api do
    namespace :v1, format: 'json' do
      resources :relationships, only: [:index, :create, :destroy]
      resources :bookmarks, only: [:index, :create, :destroy]
    end
  end

  # ========= ユーザー(public)のルーティング ================
  scope module: :public do
    root to: 'camps#index'
    get '/about' => 'homes#about'

    resources :ranks, only: [:index]
    resources :tags, only: [:index, :show]
    resources :camps, only: [:index, :show]
    resources :camp_items, only: [:index, :show]
    resources :camp_places, only: [:index, :show]
    resources :camp_item_values, only: [:new, :create]
    resources :camp_place_values, only: [:new, :create]

    resources :camp_places, only: [:index, :show] do
      resources :reservations, only: [:new, :create]
      post 'reservations/confirm' => 'reservations#confirm'
      resources :camp_place_values, only: [:index, :new, :create, :show, :destroy]
    end

    resources :camp_items, only: [:index, :show] do
      resources :camp_item_values, only: [:index, :new, :create, :show, :destroy]
    end

    resources :posts, only: [:index, :new, :create, :show, :destroy] do
      resource :favorites, only: [:create, :destroy]
      resources :post_comments, only: [:create, :destroy]
    end

    resources :users, only: [:index, :show, :edit, :update] do
      resources :bookmarks, only: [:index]
      resources :reservations, only: [:index, :show]
      resource :relationships, only: [:create, :destroy]
      member do
        get 'following'
        get 'followers'
        get 'favorites'
        get 'post'
      end
    end
  end

  # ========= 管理者(admin)のルーティング ================
  namespace :admins do
    resources :reservations, only: [:index, :show]
    resources :camp_places
    resources :camp_items
    resources :users, only: [:index, :show]
  end
end

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
    <div class="small text-center text-muted pt-3">
      <p class="text-light">© 2021 Beginner's Camp </p>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="sticky-top">
  <nav class="navbar navbar-expand-lg navbar-dark">
      <h1 class="navbar-brand font-weight-bold">
        <%= link_to root_path do %>
          <%= image_tag asset_path("Beginner's Camp.logo.png"), class: "header-logo" %>
        <% end %>
      </h1>

      <button class="navbar-toggler toggler-example humberger" type="button" data-toggle="collapse" data-target="#navbarTabContent" aria-controls="navbarTabContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="dark-blue-text">
          <i class="fas fa-bars fa-1x"></i>
        </span>
      </button>

      <% if admin_signed_in? %>
      <!--アドミンがログインしている時 -->
      <div class="collapse navbar-collapse" id="navbarTabContent">
        <ul class="navbar-nav font-weight-bold">
          <li class="nav-item ml-1"><%= link_to "予約一覧", admins_reservations_path, class: 'nav-link' %></li>
          <li class="nav-item ml-1"><%= link_to "ユーザー一覧", admins_users_path, class: 'nav-link' %></li>
          <li class="nav-item ml-1"><%= link_to "キャンプ場投稿履歴", admins_camp_places_path, class: 'nav-link' %></li>
          <li class="nav-item ml-1"><%= link_to "キャンプ用品投稿履歴", admins_camp_items_path, class: 'nav-link' %></li>
          <li class="nav-item ml-1"><%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'nav-link' %></li>
        </ul>
      </div>
      <% elsif user_signed_in? %>
      <!--ユーザーがログインしている時 -->
        <div class="collapse navbar-collapse" id="navbarTabContent">
          <ul class="navbar-nav font-weight-bold mt-3">
            <li class="nav-item"><%= link_to "ホーム", camps_path, class: 'nav-link' %></li>
            <li class="nav-item"><%= link_to "マイページ", user_path(current_user.id), class: 'nav-link' %></li>
            <li class="nav-item"><%= link_to "ユーザー一覧", users_path, class: 'nav-link' %></li>
            <li class="nav-item ml-1"><%= link_to "ランキング", ranks_path, class: 'nav-link' %></li>
            <li class="nav-item ml-1"><%= link_to "みんなのキャンプ", posts_path, class: 'nav-link' %></li>
            <li class="nav-item ml-1"><%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'nav-link' %></li>
          </ul>
        </div>
      <% else %>
      <!-- ログインしていない時 -->
        <div class="collapse navbar-collapse guest-nav" id="navbarTabContent">
          <ul class="navbar-nav font-weight-bold">
            <li class="nav-item"><%= link_to "Beginner'sCampとは", about_path, class: 'nav-link' %></li>
            <li class="nav-item ml-1"><%= link_to "新規登録", new_user_registration_path, class: 'nav-link' %></li>
            <li class="nav-item ml-1"><%= link_to "ログイン", new_user_session_path, class: 'nav-link' %></li>
          </ul>
        </div>
      <% end %>
  </nav>
</header>

app/views/layouts/_search.html.erb
<div class="search-box">
  <%= form_tag(camp_places_path,:method => 'get', id: "search-form") do %>
    <%= text_field_tag :search, '', placeholder: "検索ワード", class: 'search-left' %>
    <span class="search-right">
      <i class="fa fa-search search-btn mt-1 ml-3", onclick="checkText()"></i>
    </span>
  <% end %>
</div>

<script>
function checkText() {
  $('#search-form').submit();
}
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BeginnersCamp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <script src="https://kit.fontawesome.com/ea883a78be.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <p id="notice"><%= flash[:notice] %></p>
    <p id="alert"><%= flash[:alert] %></p>
    <main>
      <%= yield %>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>